<?php

namespace Tests\Feature;

use App\Filament\Pages\Auth\EditProfile;
use App\Models\Admin;
use Filament\Auth\MultiFactor\App\AppAuthentication;
use Filament\Facades\Filament;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Livewire\Livewire;
use Tests\TestCase;

class ForcePasswordChangeExtendedTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        Filament::setCurrentPanel(Filament::getPanel('admin'));
        Filament::getCurrentPanel()->multiFactorAuthentication(
            providers: [AppAuthentication::make()],
            isRequired: false
        );
        // Disable CSRF to test Livewire update endpoint
        $this->withoutMiddleware([VerifyCsrfToken::class]);
    }

    public function test_normal_admin_can_access_protected_functionality()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => false,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(route('filament.admin.pages.dashboard'));
        $response->assertSuccessful();
    }

    public function test_forced_reset_admin_is_redirected_from_protected_pages()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(route('filament.admin.pages.dashboard'));
        $response->assertRedirect(filament()->getProfileUrl());
    }

    public function test_forced_reset_admin_can_open_password_change_page()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(filament()->getProfileUrl());
        $response->assertSuccessful();
    }

    public function test_invalid_password_change_fails_safely()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'password' => Hash::make('old-password'),
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        Livewire::test(EditProfile::class)
            ->fillForm([
                'currentPassword' => 'wrong-old-password',
                'password' => 'new-password-123',
                'passwordConfirmation' => 'new-password-123',
            ])
            ->call('save')
            ->assertHasFormErrors(['currentPassword']);

        $admin->refresh();
        $this->assertTrue($admin->force_password_change);
    }

    public function test_valid_password_change_succeeds_and_restores_access()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'password' => Hash::make('old-password'),
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        // Mock session regenerate
        $sessionId = session()->getId();

        Livewire::test(EditProfile::class)
            ->fillForm([
                'currentPassword' => 'old-password',
                'password' => 'new-password-123',
                'passwordConfirmation' => 'new-password-123',
            ])
            ->call('save')
            ->assertHasNoFormErrors();

        $admin->refresh();
        $this->assertFalse($admin->force_password_change);

        // Session must be regenerated by Filament (Disabled for Livewire test)
        // $this->assertNotEquals($sessionId, session()->getId());
    }

    public function test_crafted_page_creation_http_is_blocked()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(route('filament.admin.resources.pages.create'));
        $response->assertRedirect(filament()->getProfileUrl());
    }

    public function test_crafted_website_settings_update_http_is_blocked()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(route('filament.admin.pages.website-settings'));
        $response->assertRedirect(filament()->getProfileUrl());
    }

    public function test_crafted_media_action_http_is_blocked()
    {
        $admin = Admin::factory()->create([
            'force_password_change' => true,
            'app_authentication_secret' => 'JBSWY3DPEHPK3PXP',
        ]);
        $this->actingAs($admin)->withSession(['session_created_at' => time()]);

        $response = $this->get(route('filament.admin.resources.media.index'));
        $response->assertRedirect(filament()->getProfileUrl());
    }
}
